### ISSUE TITLE
setSequencerPlaybackRate

### ISSUE THREAD

**Issue by mattjklassen** [ooper-shlab/AVAEMixerSample-Swift#2]
Changing playback rate of sequencer wasn't working.

Fixed by replacing the one line in func setSequencerPlaybackRate with:

self.audioEngine?.sequencerPlaybackRate = sender.value

(instead of:  self.audioEngine?.sequencerCurrentPosition = Double(sender.value)  )

**Comment by ooper-shlab** [comment]
Thanks for reporting. I'll check it later.

**Comment by ooper-shlab** [comment]
Sorry for being so late. Your suggestion is exactly the same as the code should be. I really appreciate your cooperation.
